AllCops:
  TargetRubyVersion: 2.2
  TargetRailsVersion: 4.2
  Exclude:
    - '*.spec'
    - 'Rakefile'

Rails:
  Enabled: true

# Don't enforce documentation
Style/Documentation:
  Enabled: false

# Force before_filter until upgrade to Rails 4
Rails/ActionFilter:
  EnforcedStyle: action

Metrics/MethodLength:
  Max: 40

Metrics/LineLength:
  Max: 190

Style/WordArray:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Lint/BooleanSymbol:
  Enabled: false

# Support both ruby19 and hash_rockets
Style/HashSyntax:
  EnforcedStyle: no_mixed_keys

Metrics/AbcSize:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Performance/FixedSize:
  Exclude:
    - 'test/**/*'

Metrics/BlockLength:
  Exclude:
    - 'test/**/*'

Metrics/ClassLength:
  Max: 200
  Exclude:
    - 'test/**/*'

Lint/AmbiguousBlockAssociation:
  Enabled: false

Style/ClassAndModuleChildren:
  Exclude:
    - 'test/**/*'
    - 'app/controllers/concerns/foreman/**/*'
